import type { Plan } from "@/src/types/billing";

export const PLANS: Plan[] = [
  {
    id: "free",
    name: "Free",
    slug: "free",
    description: "Для початку знайомства з додатком",
    monthlyPrice: 0,
    yearlyPrice: 0,
    currency: "USD",
    maxAccounts: 2,
    maxTransactionsPerMonth: 50,
    features: [
      { label: "До 2 рахунків", included: true },
      { label: "50 транзакцій на місяць", included: true },
      { label: "Бюджети та категорії", included: true },
      { label: "Базовий дашборд", included: true },
      { label: "Симулятор інвестицій", included: false },
      { label: "Необмежені транзакції", included: false },
      { label: "Необмежені рахунки", included: false },
      { label: "Експорт у CSV / PDF", included: false },
      { label: "Пріоритетна підтримка", included: false },
    ],
  },
  {
    id: "pro",
    name: "Pro",
    slug: "pro",
    description: "Для тих, хто серйозно відносяться до фінансів",
    monthlyPrice: 7.99,
    yearlyPrice: 5.99,
    currency: "USD",
    stripe_price_id_monthly: process.env.NEXT_PUBLIC_STRIPE_PRO_MONTHLY ?? "",
    stripe_price_id_yearly: process.env.NEXT_PUBLIC_STRIPE_PRO_YEARLY ?? "",
    maxAccounts: null,
    maxTransactionsPerMonth: null,
    badge: "Найпопулярніший",
    highlighted: true,
    features: [
      { label: "Необмежені рахунки", included: true },
      { label: "Необмежені транзакції", included: true },
      { label: "Бюджети та категорії", included: true },
      { label: "Розширений дашборд", included: true },
      { label: "Симулятор інвестицій", included: true, highlight: true },
      { label: "Експорт у CSV / PDF", included: true },
      { label: "Боргові трекери", included: true },
      { label: "Повторювані транзакції", included: true },
      { label: "Пріоритетна підтримка", included: false },
    ],
  },
  {
    id: "lifetime",
    name: "Lifetime",
    slug: "lifetime",
    description: "Одна оплата — назавжди",
    monthlyPrice: 0,
    yearlyPrice: 0,
    lifetimePrice: 149,
    currency: "USD",
    stripe_price_id_lifetime: process.env.NEXT_PUBLIC_STRIPE_LIFETIME ?? "",
    maxAccounts: null,
    maxTransactionsPerMonth: null,
    badge: "Найвигідніше",
    features: [
      { label: "Все з Pro назавжди", included: true },
      { label: "Необмежені рахунки", included: true },
      { label: "Необмежені транзакції", included: true },
      { label: "Симулятор інвестицій", included: true, highlight: true },
      { label: "Всі майбутні функції", included: true, highlight: true },
      { label: "Експорт у CSV / PDF", included: true },
      { label: "Пріоритетна підтримка", included: true, highlight: true },
      { label: "Без повторних платежів", included: true, highlight: true },
    ],
  },
];

export function getPlanBySlug(slug: string) {
  return PLANS.find((p) => p.slug === slug);
}